<h1>DATA PREPROCESSING</h1>

Let's Load the required packages. <br/>
first of all,we import numpy,matplotlib and pandas

In [1]:
# importing packgaes
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Lets load data in our dataframe
dataset=pd.read_csv('Data_Preprocessing/Data.csv')

In [3]:
# Lets see the data
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
# we have 5 columns, we have to find the feature column and the target column 
# so, country,age and salary are features of datasets and we have to find the user purcheased the items or not
# so,purchased is the target column

In [5]:
# Now we have to separate our datasets into features and in targets datasets
X=dataset.iloc[:,:-1].values

# this iloc selects all the columns except the last one

In [6]:
X #So,we have features matrix

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
# lets make our target matrix
y=dataset.iloc[:,3].values
# third columns is the target columns

In [8]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
# In our datasets some values may be missioning and we have to take care of that missing values.If we remove 
# the missing row then that data may contains senseteive data..so we have to handle the data
# One method we can handle with placing the missiong values with the average of that column

In [10]:
# we will handle that missing data using the sklearn 
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)
# so, here we will replace NaN from the datasets with mean and the 3rd parameter axis=0 means we will apply
# along with column wisw and axis=1 means we will apply crow wise
# so,in our case in features matrix data is misssing so we will apply column wise
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

# so applying the imputer method,we use fit method and we will not apply in all the columns so,int the missing column
# 1 and 2 so,we will apply in the column 1 and 2 
# after that we will apply transform the imputer 

/home/devilshacker/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [11]:
# so lets see our datasets
X
# so our in our dtasets in 1st and 2nd column we have successfully replace nan values with mean of that column

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
# Now our next step is to convert the categorical variablles lin column 0 and column 3 .
# so,to apply machine learning algorithms on that features we have to convert these into label encoding
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

In [13]:
# so lets see our datasets
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [14]:
# our categorical variable are converted into the 0,1,2
# and here we will have problem ,our machine learning algorithms understand that 2 is greater than others so,
# so,germany is converted into 2 encoding 
# we have to fix this issue so
# lets import onehotencoder

from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features=[0])#here catagorical_features is paarameters 
X=onehotencoder.fit_transform(X).toarray()

/home/devilshacker/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/devilshacker/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
# now lets convert our target categorical variables into encoding
y=dataset.iloc[:,3].values
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [16]:
y#so our target varibale is converted into 0  and 1
# here 0=No,1=Yes

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [17]:
# Now lets split our datasets into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# here we split our datasets into x_train,x_text,y_train and y_test
# train_test_split takes X as independent variable y is the dependent variable ie target variable a
# test_size=0.2 menas we will use 20% of data for testing and that 20% of data will not use for training

In [18]:
# features scaling
# features scaling means scaling the data into same range..this is because most of the machine learning algorithms use 
# euclidian distance so our data having lower value will be dominated by the higher value
# we have two method of scaling normalization and standrization
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
# lets transform x_train into standrd scaling
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)#we dont need fit_transform because we have already loaded  fit_tranform in X_train

In [19]:
X_train
# here our data is scaled into stadrd scaler

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [20]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])